### ISSUE TITLE
is this fix merged in luci kernel for 3rd party displays..thank you..

### ISSUE THREAD

**Issue by joydolma** [d4rk-lucif3r/Tissot-4.9-Q_kernel#19]
https://github.com/LineageOS/android_kernel_xiaomi_msm8953/pull/8/commits/826a12534c4797d59701a67d229697e6607cfd40

**Comment by d4rk-lucif3r** [comment]
Hey there 
This fix is already merged in my sources.
For your [reference](https://github.com/d4rk-lucif3r/LuciferKernel/commit/73f16ee7fea4b8cbd7fb301a61d895ea138e25e8)
